name: Publish package to npm and update flow catalog

on:
  release:
    types: [published] # Trigger workflow when a release is published
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Node.js and .npmrc file to publish to npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          
      # Install dependencies
      - name: Install dependencies
        run: npm install
      
      # Publish to npm
      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      # Verify Published Package (optional)
      - name: Verify Published Package
        run: npm info node-red-contrib-convert-kitchen
        
  update-flow:
    runs-on: ubuntu-latest
    name: Node-Red Flow Refresh
    needs: build
    steps:
    - name: POST
      uses: hacksore/node-red-flow@v2
      with:
        repo: 'node-red-contrib-convert-kitchen'
